spring:
  datasource:
    url: jdbc:h2:mem:TEST;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  mail:
    host: hello.smtp.com
    port: 587
    username: email@example.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

error:
  whitelabel:
    enabled: false
server:
  error:
    whitelabel:
      enabled: false

application:
  security:
    jwt:
      secret-key: zdtlD3JK56m6wTTgsNFhqzjqP
      expiration: 300 # secs
      refresh-token:
        expiration: 18000 #secs